import {StringResource} from './Strings';

export class En implements StringResource {
  api_document = 'API documents';
  write_code = 'Write code';
  login = 'Login';
  logout = 'Logout';
  sign_up = 'Sign up';
  save = 'Save';
  loading = 'Loding...';
  bad_request = 'Bad request.';
  login_title = 'Login';
  sign_up_title = 'Sign Up';
  field_label_account = 'Account...';
  field_label_password = 'Password...';
  field_label_name = 'Team Name...';
  field_label_member1 = 'Member 1...';
  field_label_member2 = 'Member 2...';
  field_label_member3 = 'Member 3...';
  field_label_member4 = 'Member 4...';
  field_label_member5 = 'Member 5...';
  field_label_app_key = 'App Key...';
  logout_message = 'You have been logout.';
  fight = 'Fight';
  fighting = 'Fighting...';
  members = 'Memembers';
  service_description = 'Write A.I. using JavaScript.';
  service_benefit = 'Your skills get better by competing with the rival.';
  wins = 'wins';
  losses = 'losses';
  matches_title = 'Matches';
  updated_at = 'Updated at';
  view_match = 'View match';
  recent_updated_users_title = 'Recent Updated Users';
  official_match = 'Official match';
  shield = 'Shield';
  fuel = 'Fuel';
  temperature = 'Temperature';
  ammo = 'Missile ammo';
}
